#include <ultra64.h>
#include "bingo.h"
#include "bingo_objective_info.h"

static struct BingoObjectiveInfo sBingoObjectiveInfo[] = {
    { BINGO_OBJECTIVE_STAR, BINGO_ICON_STAR },
    { BINGO_OBJECTIVE_STAR_TIMED, BINGO_ICON_STAR_TIMED },
    { BINGO_OBJECTIVE_STAR_TTC_RANDOM, BINGO_ICON_STAR_TTC_RANDOM },
    { BINGO_OBJECTIVE_STAR_A_BUTTON_CHALLENGE, BINGO_ICON_STAR_A_BUTTON_CHALLENGE },
    { BINGO_OBJECTIVE_STAR_B_BUTTON_CHALLENGE, BINGO_ICON_STAR_B_BUTTON_CHALLENGE },
    { BINGO_OBJECTIVE_STAR_Z_BUTTON_CHALLENGE, BINGO_ICON_STAR_Z_BUTTON_CHALLENGE },
    { BINGO_OBJECTIVE_STAR_CLICK_GAME, BINGO_ICON_STAR_CLICK_GAME },
    { BINGO_OBJECTIVE_STAR_REVERSE_JOYSTICK, BINGO_ICON_STAR_REVERSE_JOYSTICK },
    { BINGO_OBJECTIVE_STAR_GREEN_DEMON, BINGO_ICON_STAR_GREEN_DEMON },
    { BINGO_OBJECTIVE_STAR_DAREDEVIL, BINGO_ICON_STAR_DAREDEVIL },
    { BINGO_OBJECTIVE_COIN, BINGO_ICON_COIN },
    { BINGO_OBJECTIVE_1UPS_IN_LEVEL, BINGO_ICON_1UPS_IN_LEVEL },
    { BINGO_OBJECTIVE_STARS_IN_LEVEL, BINGO_ICON_STARS_IN_LEVEL },
    { BINGO_OBJECTIVE_DANGEROUS_WALL_KICKS, BINGO_ICON_DANGEROUS_WALL_KICKS },
    { BINGO_OBJECTIVE_LOSE_MARIO_HAT, BINGO_ICON_MARIO_HAT },
    { BINGO_OBJECTIVE_BLJ, BINGO_ICON_BLJ },
    { BINGO_OBJECTIVE_BOWSER, BINGO_ICON_BOWSER },
    { BINGO_OBJECTIVE_MULTICOIN, BINGO_ICON_MULTICOIN },
    { BINGO_OBJECTIVE_MULTISTAR, BINGO_ICON_MULTISTAR },
    { BINGO_OBJECTIVE_SIGNPOST, BINGO_ICON_SIGNPOST },
    { BINGO_OBJECTIVE_RED_COIN, BINGO_ICON_RED_COIN },
    { BINGO_OBJECTIVE_EXCLAMATION_MARK_BOX, BINGO_ICON_EXCLAMATION_MARK_BOX },
    { BINGO_OBJECTIVE_AMPS, BINGO_ICON_AMP },
    { BINGO_OBJECTIVE_KILL_GOOMBAS, BINGO_ICON_KILL_GOOMBAS },
    { BINGO_OBJECTIVE_KILL_BOBOMBS, BINGO_ICON_KILL_BOBOMBS },
    { BINGO_OBJECTIVE_KILL_SPINDRIFTS, BINGO_ICON_KILL_SPINDRIFTS },
    { BINGO_OBJECTIVE_KILL_MR_IS, BINGO_ICON_KILL_MR_IS },
};

struct BingoObjectiveInfo *get_objective_info(enum BingoObjectiveType type) {
    s32 i;
    s32 size = sizeof(sBingoObjectiveInfo) / sizeof(sBingoObjectiveInfo[0]);
    for (i = 0; i < size; i++) {
        if (sBingoObjectiveInfo[i].type == type) {
            return &sBingoObjectiveInfo[i];
        }
    }
    return NULL;
}
